---
title: "Netflix"
author: "Ricardo"
date: "20/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


## Carga de datos

```{r}
#probe=read_csv("data/probe.txt")
aux=read_tsv("data/combined_data_1.txt",col_names=FALSE,n_max =10000)# leo 10^4 lo leo con tabulador para que lea una varable
aux=aux%>% mutate(fila=row_number())
filas=grep(":",aux$X1)
filas_ID= aux %>% filter( fila %in% filas )
IDs=unique(filas_ID$X1)
reps=diff(c(filas_ID$fila,max(aux$fila)+1))
length(reps)
dim(aux)
sum(reps)
combined_data_1=aux %>% mutate(ID1=rep(filas_ID$X1,times=reps)) %>% filter(!(fila %in% filas) ) %>% filter(ID1==ID1[length(IDs)])
# filtro el último pues no sé si lo he leído entero y las entradas 1:





```



Ahora arreglo la variable X1


```{r}
combined_data_1= combined_data_1 %>% separate(X1,into=c("ID_film","Score","data"),sep=",")
rm(aux,filas,filas_ID,IDs,reps)
```
Visualizo la tabla

```{r}
knitr::kable(combined_data_1)
```

